version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started
      - grep -Fq "Hello Node" index.js
  post_build:
    commands:
      - echo Build completed
